### ISSUE TITLE
Application Fails to Start with Spring Cloud Sleuth Integration

### ISSUE THREAD

**Issue by MuhammedAbduRafi** [quantics-io/multitenant-oauth2-spring-boot-starter#10] opened 2023-08-17 18:03 UTC
Hi, First and foremost, I'd like to express my gratitude for developing the `multitenant-oauth2-spring-boot-starter` library. It has been an incredibly useful tool for my projects, and I'm thankful for your hard work.

However, I've encountered an issue while trying to integrate Spring Cloud Sleuth into my project alongside this library. When attempting to start the application, I encountered the following error message:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Field interceptor in io.quantics.multitenant.oauth2.config.MultiTenantResourceServerWebMvcConfiguration$3 required a single bean, but 2 were found:
        - multiTenantJwtInterceptor: defined by method 'multiTenantJwtInterceptor' in class path resource [io/quantics/multitenant/oauth2/config/MultiTenantResourceServerWebMvcConfiguration.class]
        - org.springframework.cloud.sleuth.instrument.web.mvc.SpanCustomizingAsyncHandlerInterceptor: defined in unknown location


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

It seems that there might be a conflict between the `multiTenantJwtInterceptor` bean defined in your library and the `SpanCustomizingAsyncHandlerInterceptor` bean introduced by Spring Cloud Sleuth.

**Steps to Reproduce:**

1. Add Spring Cloud Sleuth dependencies to your project.
2. Configure the `multitenant-oauth2-spring-boot-starter` library.
3. Attempt to start the application.

**Additional Information:**

- `multitenant-oauth2-spring-boot-starter` library version: 0.3.1
- Spring Boot version: 2.7.11
- Spring Cloud version: 2021.0.6

Thank you

**Comment by jomatt** [comment] 2023-11-12 17:10
@MuhammedAbduRafi thank you for using the library - I'm happy to hear that it helps you with your projects. The issue is fixed in #12

**Closed as completed** 2023-11-12 17:11 UTC
